<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css"
          integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <title>title</title>

</head>
<body>
<div class="container pt-5">
    <nav class="navbar navbar-expand-lg navbar-light bg-light mb-5">
        <a class="navbar-brand" href="/">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/posts">Posts</a>
                </li>
            </ul>
<!--            --><?php //if (\Mvc\Library\SessionManager::isAuthenticated()): ?>
<!--                <ul class="navbar-nav ml-auto">-->
<!--                    <li class="nav-item active">-->
<!--                        <a class="nav-link" href="/admin">Admin</a>-->
<!--                    </li>-->
<!--                </ul>-->
<!--            --><?php //endif; ?>
        </div>
    </nav>

<!--    --><?php //if ($messages = \Mvc\Library\SessionManager::getMessages()): ?>
<!--        --><?php //foreach ($messages as $message): ?>
<!--            <div class="alert alert---><?php //echo $message['type'] ?><!--" role="alert">-->
<!--                --><?php //$this->esc($message['message']) ?>
<!--            </div>-->
<!--        --><?php //endforeach; ?>
<!--    --><?php //endif; ?>
